#!/usr/bin/env python3
from boiler.cli import cli as kernel

# root project command
cli = kernel.cli

# add orm cli
from shiftmedia.cli import cli as media
cli.add_command(media.cli, name='media')

# and run
cli()

